import { spawnSync } from "node:child_process"
import {
	cpSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { rewriteMarkdown } from "./links"
import { commands, sources } from "./sources"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..")
const generated = join(root, "docs-site/src/content/docs/imported")
rmSync(generated, { recursive: true, force: true })
mkdirSync(generated, { recursive: true })
for (const { file, slug, title } of sources) {
	const body = readFileSync(join(root, file), "utf8").replace(/^# .*\n/, "")
	const frontmatter = {
		title,
		slug,
		description: `${title} for dotenc.`,
		editUrl: `https://github.com/dotenc/dotenc/edit/main/${file}`,
	}
	writeFileSync(
		join(generated, `${slug.replaceAll("/", "-")}.md`),
		`---\n${JSON.stringify(frontmatter)}\n---\n\n${rewriteMarkdown(body, file)}`,
	)
}
// Help is generated by the real CLI, in an empty home, never by inspecting user identities.
const home = mkdtempSync(join(tmpdir(), "dotenc-docs-help-"))
try {
	const env = {
		PATH: process.env.PATH,
		HOME: home,
		XDG_CONFIG_HOME: home,
		XDG_CACHE_HOME: home,
		NO_COLOR: "1",
		DOTENC_SKIP_UPDATE_CHECK: "1",
	}
	let reference = `---\ntitle: Command reference\ndescription: Flags and arguments generated from the dotenc CLI.\nslug: reference/commands\neditUrl: https://github.com/dotenc/dotenc/edit/main/cli/src/program.ts\n---\n\nThis reference is generated from the CLI source in this revision. Run\n\`dotenc --version\` and \`dotenc <command> --help\` to check your installation.\nThe latest published release at this migration is **0.14.2**.\n\n:::caution[Upcoming command]\n\`doctor artifacts\` is merged on main but is not in published CLI 0.14.2.\nThe doctor help below includes that upcoming subcommand.\n:::\n\nHidden machine-use commands are included for integrations. Decryption and\ntextconv write plaintext: capture their output inside a local process and never\nforward it to an agent conversation or log. See [agent workflows](/docs/integrations/agents/).\n\n`
	for (const args of commands) {
		const result = spawnSync(
			process.execPath,
			[join(root, "cli/src/cli.ts"), ...args, "--help"],
			{ cwd: home, env, encoding: "utf8", timeout: 30000 },
		)
		if (result.status !== 0)
			throw new Error(`CLI help failed: dotenc ${args.join(" ")}`)
		reference += `## dotenc${args.length ? ` ${args.join(" ")}` : ""}\n\n\`\`\`text\n${result.stdout.trim()}\n\`\`\`\n\n`
	}
	writeFileSync(join(generated, "commands.md"), reference)
} finally {
	rmSync(home, { recursive: true, force: true })
}
mkdirSync(join(root, "docs-site/public"), { recursive: true })
for (const file of ["favicon.svg", "brand-symbol.svg"])
	cpSync(
		join(root, "website/public", file),
		join(root, "docs-site/public", file),
	)
console.log(
	`Prepared ${sources.length} canonical guides and ${commands.length} CLI help entries.`,
)

// Static Markdown endpoints let readers and agents retrieve one topic without UI markup.
const contentRoot = join(root, "docs-site/src/content/docs")
const markdownRoot = join(root, "docs-site/public/markdown")
rmSync(markdownRoot, { recursive: true, force: true })
const index: string[] = [
	"# dotenc documentation",
	"",
	"Docs for CLI 0.14.2; upcoming commands are labeled on their pages.",
	"",
]
function exportMarkdown(directory: string, prefix = "") {
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const relative = `${prefix}${entry.name}`
		if (entry.isDirectory()) {
			exportMarkdown(join(directory, entry.name), `${relative}/`)
			continue
		}
		if (!entry.name.endsWith(".md")) continue
		const source = readFileSync(join(directory, entry.name), "utf8")
		const match = source.match(/^---\n([\s\S]*?)\n---\n/)
		if (!match) throw new Error(`Missing page metadata: ${relative}`)
		const metadata = Bun.YAML.parse(match[1]) as {
			title: string
			slug?: string
		}
		const slug = metadata.slug ?? relative.replace(/\.md$/, "")
		const target = join(markdownRoot, `${slug}.md`)
		mkdirSync(dirname(target), { recursive: true })
		writeFileSync(target, source)
		index.push(
			`- [${metadata.title}](https://dotenc.org/docs/markdown/${slug}.md)`,
		)
	}
}
exportMarkdown(contentRoot)
writeFileSync(join(root, "docs-site/public/llms.txt"), `${index.join("\n")}\n`)
