/** Explicit publication list: plans, audit logs, and internal runbooks stay on GitHub. */
export const sources = [
	{
		file: "docs/INSTALLATION.md",
		slug: "getting-started/installation",
		title: "Installation",
	},
	{
		file: "docs/GITHUB_ACTIONS.md",
		slug: "ci/github-actions",
		title: "GitHub Actions",
	},
	{ file: "docs/EXPO_EAS.md", slug: "ci/expo-eas", title: "Expo / EAS" },
	{ file: "docs/VERCEL.md", slug: "ci/vercel", title: "Vercel" },
	{ file: "docs/NETLIFY.md", slug: "ci/netlify", title: "Netlify" },
	{ file: "docs/CLOUDFLARE.md", slug: "ci/cloudflare", title: "Cloudflare" },
	{ file: "docs/COOLIFY.md", slug: "ci/coolify", title: "Coolify" },
	{ file: "docs/RAILPACK.md", slug: "ci/railpack", title: "Railpack" },
	{ file: "docs/NIXPACKS.md", slug: "ci/nixpacks", title: "Nixpacks" },
	{
		file: "docs/OCI_IMAGE.md",
		slug: "ci/containers",
		title: "Container images",
	},
	{
		file: "docs/LINUX_PACKAGES.md",
		slug: "reference/linux-packages",
		title: "Linux packages",
	},
	{
		file: "vscode-extension/README.md",
		slug: "integrations/vscode",
		title: "VS Code extension",
	},
	{
		file: "SECURITY.md",
		slug: "security/model",
		title: "Security specification",
	},
] as const

export const commands = [
	[],
	["init"],
	["dev"],
	["run"],
	["whoami"],
	["env"],
	["env", "create"],
	["env", "edit"],
	["env", "list"],
	["env", "rename"],
	["env", "rotate"],
	["env", "delete"],
	["env", "encrypt"],
	["env", "decrypt"],
	["key"],
	["key", "add"],
	["key", "list"],
	["key", "remove"],
	["auth"],
	["auth", "grant"],
	["auth", "revoke"],
	["auth", "list"],
	["auth", "purge"],
	["doctor"],
	["doctor", "artifacts"],
	["config"],
	["update"],
	["tools"],
	["tools", "install-agent-skill"],
	["tools", "install-vscode-extension"],
	["tools", "install-github-diffs"],
	["textconv"],
]
